### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by Mctigger** [moskomule/senet.pytorch#1]
Hi,
did you already pretrain the models on imagenet? If so could you provide the weights for these model?

Best wishes
Tim

**Comment by moskomule** [comment]
Hi, 
I haven't experimented on ImageNet and indeed no plan to do that(because of restricted computational power). The authors distribute Caffe's pre-train models https://github.com/hujie-frank/SENet so if you need converting from these is a fast way.

**Comment by Mctigger** [comment]
Okay, thank you. I would have liked to not manually convert them, but seems like there is no other way!

**Comment by moskomule** [comment]
Hi, I've just added a code for ImageNet training.

**Comment by HiKapok** [comment]
@Mctigger Hi, here is one TensorFlow SE-Net with pretrained wieghts converted from Caffe. See [https://github.com/HiKapok/TF_Se_ResNe_t](url)  if you are interested in.

**Comment by Xingxiangrui** [comment]
I got pytorch SENet pretrained model here: https://github.com/Xingxiangrui/various_pyTorch_network_structure/blob/master/senet_and_pretrained.py
