### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by achaiah** [moskomule/senet.pytorch#10]
Hi,

Could you please add license to your repo so that others may use your work?

Thanks

**Comment by moskomule** [comment]
OK, I'll check and add a license.

**Comment by iCrown** [comment]
+1. Can you add some license(e.g. Apache or Mit license) for this project.

**Comment by iCrown** [comment]
+1. Can you add some license(e.g. Apache or Mit license) for this project. Thx!

**Comment by moskomule** [comment]
@achaiah , @iCrown  Sorry for late. OK, I'll add a license.

**Comment by moskomule** [comment]
I've just added the MIT license.
