### ISSUE TITLE
Reduction Ratio

### ISSUE THREAD

**Issue by lwoiceshyn** [moskomule/senet.pytorch#13]
According to the SENet paper, the reduction should be a ratio of which we use to find the number of dimensions to reduce to and expand from in the FC layers of the SE block.

In your implementation, you always reduce the dimensionality to the value of the reduction, 16:
nn.Linear(channel, reduction)

Am I misunderstanding something here? Shouldn't it be nn.Linear(channel, channel // reduction)?

**Comment by moskomule** [comment]
Hi @lwoiceshyn Thank you for your reporting.  Yes, you're right. It should be `channel//reduction`. I'll update soon and experiment again soon.
