### ISSUE TITLE
 I want to apply senet to another network

### ISSUE THREAD

**Issue by poppingcode** [moskomule/senet.pytorch#15]
I want to apply senet to another network，Do you have some examples？
（PYTORCH）
I want to know where the code is different from before and after the code.

**Comment by moskomule** [comment]
Hi, it's just replacing some part of your network with `se_module` in https://github.com/moskomule/senet.pytorch/blob/master/se_module.py. I think https://github.com/moskomule/senet.pytorch/blob/master/se_inception.py is an example.

**Comment by poppingcode** [comment]
thank you very much!!!,
I usually introduce BN-inception structure from the pytorch package, and then use the BN-inception structure of the training data, and now I want to modify and add the SE structure in the BN-inception structure, which uses the structure of SE was added to training data, do I need to rewrite a BN-inception network and then adding SE.
Then I'll take a closer look at the two websites you've just sent. I could also ask you some questions
Thank you once again.

**Comment by poppingcode** [comment]
What is the meaning of the following code？in se_inception.py
def se_inception_v3(**kwargs):
    return Inception3(**kwargs)

**Comment by moskomule** [comment]
Oh thanks, it's a typo. Should be `SEInception3`. I'll fix.
