### ISSUE TITLE
performance comparison

### ISSUE THREAD

**Issue by YanjunChen** [moskomule/senet.pytorch#16]
Thanks for your implementation in pytorch. However, can you please compare the results you tested with those published in the initial paper?  It seems there is a gap between caffe and pytroch.

**Comment by YanjunChen** [comment]
BTW, as to resnet50, the paper improve from 75.3 to 76.71 while in this implementation there is a drop when using se-resnet50. what is the difference?

**Comment by moskomule** [comment]
In the original paper, the authors do not experiment on CIFAR dataset. As for ImageNet, my computational resources are limited so I cannot find good hyper parameters.

**Comment by YanjunChen** [comment]
Thanks!
