### ISSUE TITLE
Loading the SE-ResNet50's pkl file error

### ISSUE THREAD

**Issue by TonyDongLB** [moskomule/senet.pytorch#21]
Hi,  sorry to bother you.
When I loading you pkl file, the interpreter print this 

> RuntimeError: Error(s) in loading state_dict for SE_ResNet50_feature:
	While copying the parameter named "layer2.0.se.fc.0.weight", whose dimensions in the model are torch.Size([32, 512]) and whose dimensions in the checkpoint are torch.Size([16, 512]).
	While copying the parameter named "layer2.0.se.fc.0.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([16]).
	While copying the parameter named "layer2.0.se.fc.2.weight", whose dimensions in the model are torch.Size([512, 32]) and whose dimensions in the checkpoint are torch.Size([512, 16]).
	While copying the parameter named "layer2.1.se.fc.0.weight", whose dimensions in the model are torch.Size([32, 512]) and whose dimensions in the checkpoint are torch.Size([16, 512]).
	While copying the parameter named "layer2.1.se.fc.0.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([16]).
	While copying the parameter named "layer2.1.se.fc.2.weight", whose dimensions in the model are torch.Size([512, 32]) and whose dimensions in the checkpoint are torch.Size([512, 16]).
	While copying the parameter named "layer2.2.se.fc.0.weight", whose dimensions in the model are torch.Size([32, 512]) and whose dimensions in the checkpoint are torch.Size([16, 512]).
	While copying the parameter named "layer2.2.se.fc.0.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([16]).
	While copying the parameter named "layer2.2.se.fc.2.weight", whose dimensions in the model are torch.Size([512, 32]) and whose dimensions in the checkpoint are torch.Size([512, 16]).
	While copying the parameter named "layer2.3.se.fc.0.weight", whose dimensions in the model are torch.Size([32, 512]) and whose dimensions in the checkpoint are torch.Size([16, 512]).
	While copying the parameter named "layer2.3.se.fc.0.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([16]).
	While copying the parameter named "layer2.3.se.fc.2.weight", whose dimensions in the model are torch.Size([512, 32]) and whose dimensions in the checkpoint are torch.Size([512, 16]).
	While copying the parameter named "layer3.0.se.fc.0.weight", whose dimensions in the model are torch.Size([64, 1024]) and whose dimensions in the checkpoint are torch.Size([16, 1024]).
	While copying the parameter named "layer3.0.se.fc.0.bias", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([16]).
	While copying the parameter named "layer3.0.se.fc.2.weight", whose dimensions in the model are torch.Size([1024, 64]) and whose dimensions in the checkpoint are torch.Size([1024, 16]).
	While copying the parameter named "layer3.1.se.fc.0.weight", whose dimensions in the model are torch.Size([64, 1024]) and whose dimensions in the checkpoint are torch.Size([16, 1024]).
	While copying the parameter named "layer3.1.se.fc.0.bias", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([16]).
	While copying the parameter named "layer3.1.se.fc.2.weight", whose dimensions in the model are torch.Size([1024, 64]) and whose dimensions in the checkpoint are torch.Size([1024, 16]).
	While copying the parameter named "layer3.2.se.fc.0.weight", whose dimensions in the model are torch.Size([64, 1024]) and whose dimensions in the checkpoint are torch.Size([16, 1024]).
	While copying the parameter named "layer3.2.se.fc.0.bias", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([16]).
	While copying the parameter named "layer3.2.se.fc.2.weight", whose dimensions in the model are torch.Size([1024, 64]) and whose dimensions in the checkpoint are torch.Size([1024, 16]).
	While copying the parameter named "layer3.3.se.fc.0.weight", whose dimensions in the model are torch.Size([64, 1024]) and whose dimensions in the checkpoint are torch.Size([16, 1024]).
	While copying the parameter named "layer3.3.se.fc.0.bias", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([16]).
	While copying the parameter named "layer3.3.se.fc.2.weight", whose dimensions in the model are torch.Size([1024, 64]) and whose dimensions in the checkpoint are torch.Size([1024, 16]).
	While copying the parameter named "layer3.4.se.fc.0.weight", whose dimensions in the model are torch.Size([64, 1024]) and whose dimensions in the checkpoint are torch.Size([16, 1024]).
	While copying the parameter named "layer3.4.se.fc.0.bias", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([16]).
	While copying the parameter named "layer3.4.se.fc.2.weight", whose dimensions in the model are torch.Size([1024, 64]) and whose dimensions in the checkpoint are torch.Size([1024, 16]).
	While copying the parameter named "layer3.5.se.fc.0.weight", whose dimensions in the model are torch.Size([64, 1024]) and whose dimensions in the checkpoint are torch.Size([16, 1024]).
	While copying the parameter named "layer3.5.se.fc.0.bias", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([16]).
	While copying the parameter named "layer3.5.se.fc.2.weight", whose dimensions in the model are torch.Size([1024, 64]) and whose dimensions in the checkpoint are torch.Size([1024, 16]).
	While copying the parameter named "layer4.0.se.fc.0.weight", whose dimensions in the model are torch.Size([128, 2048]) and whose dimensions in the checkpoint are torch.Size([16, 2048]).
	While copying the parameter named "layer4.0.se.fc.0.bias", whose dimensions in the model are torch.Size([128]) and whose dimensions in the checkpoint are torch.Size([16]).
	While copying the parameter named "layer4.0.se.fc.2.weight", whose dimensions in the model are torch.Size([2048, 128]) and whose dimensions in the checkpoint are torch.Size([2048, 16]).
	While copying the parameter named "layer4.1.se.fc.0.weight", whose dimensions in the model are torch.Size([128, 2048]) and whose dimensions in the checkpoint are torch.Size([16, 2048]).
	While copying the parameter named "layer4.1.se.fc.0.bias", whose dimensions in the model are torch.Size([128]) and whose dimensions in the checkpoint are torch.Size([16]).
	While copying the parameter named "layer4.1.se.fc.2.weight", whose dimensions in the model are torch.Size([2048, 128]) and whose dimensions in the checkpoint are torch.Size([2048, 16]).
	While copying the parameter named "layer4.2.se.fc.0.weight", whose dimensions in the model are torch.Size([128, 2048]) and whose dimensions in the checkpoint are torch.Size([16, 2048]).
	While copying the parameter named "layer4.2.se.fc.0.bias", whose dimensions in the model are torch.Size([128]) and whose dimensions in the checkpoint are torch.Size([16]).
	While copying the parameter named "layer4.2.se.fc.2.weight", whose dimensions in the model are torch.Size([2048, 128]) and whose dimensions in the checkpoint are torch.Size([2048, 16])

it seems that the model doesn't fit this checkpoint, and this size of checkpoint would be wrong?
Thank you for your reply!

**Comment by moskomule** [comment]
Hi, I trained the model on PyTorch v0.3.x, and that might be the reason. Please refer other closed issues. I plan to train it on v0.4.1 as soon as resources are available.

**Comment by hitlk** [comment]
As said in #13, the pre-trained model might be trained using old code.

**Comment by nicktao9** [comment]
yes,I got this error also,Thanks for your excellent work. the model is best.thanks again
