### ISSUE TITLE
fine tune on ResNet with SE layer

### ISSUE THREAD

**Issue by vra** [moskomule/senet.pytorch#3]
Hi,
Thanks for your work on this, it's helpful. I wonder how to fine tune on pretrained models provided by Pytorch Website and add SE layer into ResNet? thanks in advance.

**Comment by moskomule** [comment]
Hi, you mean you like to use ResNet's weight for "SENet's ResNet part" and use arbitrary weights for "SENet's SE blocks"?

**Comment by vra** [comment]
Yes that's exactly what I need. Could you please give some hints on how to achieve this? Thank you

**Comment by moskomule** [comment]
Ok.  

```
resnet = torchvision.models.resnet18(pretrained=True, num_classes=1000)
senet = se_resnet18(num_classes=1000)
```

Then `senet.state_dict()` and `resnet.state_dict()` return `OrderedDict` object, which is ordered dictionary. So

```
re_dict = resnet.state_dict()
se_dict = senet.state_dict()
for res_key, res_value in re_dict.items():
    if key in se_dict:
        se_dict[key] = res_value
```

overwrites senet's weight.

**Comment by vra** [comment]
Thanks for your guide, I will try it.

**Comment by slighting666** [comment]
@vra  hi，can you tell me how to solve it？ i miss the same  question，thanks
