### ISSUE TITLE
 pre-training model of resnet101

### ISSUE THREAD

**Issue by gaichengyuan** [moskomule/senet.pytorch#31]
Hello, thank you in advance. Can you provide the pre-training model of resnet101?

**Comment by moskomule** [comment]
At this moment, I don't have enough computational resource for this project anymore.
But I add my to-do pre-training of Se-ResNet-101.

**Comment by skq-5233** [comment]
Hello there! Is there a pytorch version of the Se-ResNet-101 pre-trained model? Thank you! @moskomule
