### ISSUE TITLE
pretrained weight file

### ISSUE THREAD

**Issue by ericsqxd** [moskomule/senet.pytorch#32]
Could you please  share the pretrained weight file of Pytorch V0.4.0?

**Comment by moskomule** [comment]
Basically, there is no difference between v1.0 and v0.4 so if you want to use the pretrained weight, update PyTorch.

**Comment by MichaelGuoo** [comment]
hi moskomule
Could you please share the pretrained weight file of SE-inceptionv3 on Imagenet?

**Comment by moskomule** [comment]
As issue #31 , at this moment, I don't have enough computational resource for this project anymore.

**Comment by d5195295** [comment]
import torch.hub
hub_model = torch.hub.load('moskomule/senet.pytorch','se_resnet50',pretrained=True,)
Why do I use the above command but can't download it?

The error message is as follows:
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by moskomule** [comment]
It's PyTorch's bug.
