### ISSUE TITLE
loss issue

### ISSUE THREAD

**Issue by niuniu111** [moskomule/senet.pytorch#36]
when run python cifar.py runs SE-ResNet50 with Cifar10 dataset，at about 150 steps, the  accuracy is worse and the mutation is better, and the loss curve also fluctuates.I want to discuss the reason with you

**Comment by moskomule** [comment]
If I understand correctly, SE-ResNet 50 is for the ImageNet size (224x224) only.
For CIFAR size, use SeResNet-{20,56,...}
