### ISSUE TITLE
Can't load pretrained weight in transfer learning

### ISSUE THREAD

**Issue by DRL36** [moskomule/senet.pytorch#39]
Hi, I'm doing se-resnet on my custom dataset. But when I set pretrained=True, I always get such error: invalid hash value (expected "60a8950a85b2b", got "dfe331c8d9c60c2585a2f6c581dd72
04637b9f16ab9e18b50c953d460107a18b").
Any ideas?

**Comment by moskomule** [comment]
Hi, I know this issue but I still cannot solve it. I'm afraid this is Dropbox's issue because when I modify the hash part ("60a8950a85b2b") to `dfe331c...`, the hash of the downloaded file will change.

**Comment by moskomule** [comment]
I change the hosting site of the weight to GitHub, and the problem is fixed.
