### ISSUE TITLE
How to resume from a checkpint file?

### ISSUE THREAD

**Issue by chituma110** [moskomule/senet.pytorch#41]
My training with  senet on ImageNet was unexpectedly interruped. How to resume the training from a checkpoint with distributed setting?

**Comment by moskomule** [comment]
`Trainer` has `resume(self, path)`. If you use my code, I think that just specifying the path to the saved weight is enough.

**Comment by chituma110** [comment]
I have resume the training successfully, but when I add "-distributed" flag， the training process broke down

**Comment by moskomule** [comment]
OK, I'll check that problem.

**Comment by moskomule** [comment]
I think now the `resume` works as expected.
