### ISSUE TITLE
Further arguments required in SEBottleneck

### ISSUE THREAD

**Issue by BenSaunders27** [moskomule/senet.pytorch#42]
When integrating the SEBottleneck block into ResNet, I received the error:
 >"__init__() takes from 3 to 6 positional arguments but 9 were given" 

at the following part of class ResNet, def _make_layer:

`layers.append(block(self.inplanes, planes, stride, downsample, self.groups,
                            self.base_width, previous_dilation, norm_layer))`

----

I found that this was because the "SEBottleneck" class does not contain all arguments found in the "Bottleneck" class, missing "groups, base_width, dilation & norm_layer":

`class SEBottleneck(nn.Module):
def __init__(self, inplanes, planes, stride=1, downsample=None, reduction=16):`

`class Bottleneck(nn.Module):
    def __init__(self, inplanes, planes, stride=1, downsample=None, groups=1,
                 base_width=64, dilation=1, norm_layer=None):`

----

In order to solve this, I added in these required arguments into the SEBottleneck class, but I am unsure how it worked correctly without these? I am highlighting this as a potential required change to the senet.pytorch code

**Comment by moskomule** [comment]
Hi, thank you for your report. This change is introduced from torchvision v0.3 and I'm modifying the code https://github.com/moskomule/senet.pytorch/pull/40 .

**Comment by moskomule** [comment]
I think now it's fixed.
