### ISSUE TITLE
No bias in SE module

### ISSUE THREAD

**Issue by bonlime** [moskomule/senet.pytorch#44]
Hi,
I've been looking through your code and found that you explicitly set bias to `False` in SE Module https://github.com/moskomule/senet.pytorch/blob/506fff16001e539e4a086b11307b0ec23eb3fb8f/senet/se_module.py#L9
While authors of the oirginal paper [use bias](https://github.com/hujie-frank/SENet/blob/0262d43d44c561fd53c3dba210cc8bacfc60500d/models/SE-ResNet-50.prototxt#L200)
Is there any particular reason why you didn't use bias in your models, or it's just a bug?

**Comment by moskomule** [comment]
Hi, I don't remember why I removed the bias terms since I implemented SENet two years ago. If you notice performance improvement, could you please send a PR?

**Comment by bonlime** [comment]
I ended up writing a version **with** bias in order to be able to load weights from [pretrained-models.pytorch](https://github.com/Cadene/pretrained-models.pytorch). I didn't make any comparison between `bias=True` and `bias=False`
