### ISSUE TITLE
About  some parameters in training

### ISSUE THREAD

**Issue by Totoro-wen** [moskomule/senet.pytorch#46]
I can't understand the function of the following parameters, can you write it more clearly.
   ```
    p.add_true("--distributed")
    p.add_int("--local_rank", default=-1)
    p.add_str("--init_method", default="env://")
    p.add_str("--backend", default="nccl")
```
Thanks.

**Comment by moskomule** [comment]
Hi, they are for distributed training. Check https://github.com/pytorch/examples/tree/master/imagenet for details.
