### ISSUE TITLE
About the reduction...

### ISSUE THREAD

**Issue by JiaquanYe** [moskomule/senet.pytorch#51]
hey, I have compare your code se_resnet and the paper, in your code, the reduction is fix to 16, however, in the paper, the reduction get a higher value in deeper stage of resnet.

so, is it necessary to change the reduction in the deeper stage?

**Comment by moskomule** [comment]
Thank you for comment. I did this project long before and do not remember the details of the paper. It may be different between the versions of arXiv paper.
