### ISSUE TITLE
the pretrained model on se-net50

### ISSUE THREAD

**Issue by dyl25984** [moskomule/senet.pytorch#53]
hello, I want to download the pre-trained model on se-resnet50 on ImageNet, but the speed is extremely low with only 1.5KB/s. So I wonder if you can send it to me by email.My email address is dyl25984@mail.ustc.edu.cn. Thank you very much.

**Comment by moskomule** [comment]
Hi, I have no way to send you the weight file by attaching on email, because of the file-size limit.
Are you in China?

**Comment by dyl25984** [comment]
yes

**Comment by moskomule** [comment]
https://github.com/moskomule/senet.pytorch/issues/52 reports the same problem. In my environment accessing from Japan, the speed is over 5MB/s so I don't think it's the problem of the GitHub side.
