### ISSUE TITLE
import homura ERROR

### ISSUE THREAD

**Issue by henbucuoshanghai** [moskomule/senet.pytorch#54]
verbose)
  File "/home/lanaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 923, in _prepare_ldflags
    extra_ldflags.append('-L{}'.format(_join_cuda_home('lib64')))
  File "/home/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1146, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install roo

**Comment by henbucuoshanghai** [comment]
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install roo

**Comment by moskomule** [comment]
The latest `homura` compiles cuda code at runtime. So please just follow the error message.
Maybe the following will help you:

```console
pip uninstall homura
pip install -U git+https://github.com/moskomule/homura@v0.6
```

**Comment by henbucuoshanghai** [comment]
tks    it works
besides  homura is ??? i have never heard of it ...

**Comment by moskomule** [comment]
It's my own library.

**Comment by henbucuoshanghai** [comment]
.... great!!  cool!!!....
