### ISSUE TITLE
cannot import name 'DistributedSupervisedTrainer' from 'homura.trainers

### ISSUE THREAD

**Issue by 19v05137** [moskomule/senet.pytorch#57]
Thanks for your contribution！When I learned your senet.pytorch code (https://github.com/moskomule/senet.pytorch) and found such an error "ImportError: cannot import name 'DistributedSupervisedTrainer' from 'homura.trainers'", I checked your trainer.py file, no “DistributedSupervisedTrainer” function found. Where did I go wrong? Thank you

**Comment by DancingJane** [comment]
I have the same problem. Did you solve it ?

**Comment by moskomule** [comment]
https://github.com/moskomule/senet.pytorch/commit/3b2a90ad9bcebe6ef004da614f2ecd2d1e29fdb1 would solve this problem. Please check.
