### ISSUE TITLE
Will you open source the FasterAA?

### ISSUE THREAD

**Issue by JiyueWang** [moskomule/senet.pytorch#58]
I have read the paper and I think it's a great idea to make the policy 'backpropable' with GAN structure. I  really want to apply the algorithm to my project.  Will you open the source code. That would be great.

**Comment by moskomule** [comment]
Hi, thank you for reading our paper. After the acceptance of our paper, we will open-source Faster AutoAugment.

**Comment by JiyueWang** [comment]
Aha! This article deserves a top conference acceptance. :d 
May I ask the schedule?

**Comment by moskomule** [comment]
Thanks, I hope so. Stay tuned!

**Comment by JiyueWang** [comment]
I have another question. Have you read the new ICLR paper 'Adversarial data augment'? I think it will be a really powerful algorithm if you modify your discriminator part as they do.

**Comment by JiyueWang** [comment]
Anything new about fasterAA yet？

**Comment by moskomule** [comment]
At the moment, no.

**Comment by moskomule** [comment]
I will release FasterAA in https://github.com/moskomule/dda in a couple of weeks.
