### ISSUE TITLE
about avg_pool in se_module.py

### ISSUE THREAD

**Issue by zz10001** [moskomule/senet.pytorch#59]
Hi,
Thanks for your great work, I notice that in your **SELayer**, You use **self.avg_pool = nn.AdaptiveAvgPool2d(1)**, if my input is **512*512**, should i change it to a large number?

**Comment by moskomule** [comment]
Hi, I don't think so because it's used to make the feature `batch_size x channel_size`.

**Comment by zz10001** [comment]
Thanks for your kind help, I will see it later!
