### ISSUE TITLE
Backbone of object detection

### ISSUE THREAD

**Issue by kp-1** [moskomule/senet.pytorch#60]
Excuse me, can you give me some help on what I should do if I want to use Senet as the backbone  in object detection? Could i use the pretained model and how to use it. thanks!

**Comment by moskomule** [comment]
Hi, it depends on which detection network you want to use. For example, in FasterRCNN, I think what you need to do is just use the SENet model as the backbone.
https://github.com/pytorch/vision/blob/master/torchvision/models/detection/faster_rcnn.py#L143

**Comment by kp-1** [comment]
Yeah,thank you very much, but maybe I didn't make it clear.I want to know if I need to make changes to senet, such as adding DCN to senet to be the backbone of object detection, then what should  I do?Still use senet's pre-training weight?or any else?

**Comment by moskomule** [comment]
If I understand correctly, the torchvision's implementation loads the PyTorch's ResNet-50. So it should be just few line of modification.

**Comment by kp-1** [comment]
Ok, really thanks for your patience. And I have last question: is 'class CifarSEBasicBlock(nn.Module),
class CifarSEResNet(nn.Module), class CifarSEPreActResNet(CifarSEResNet)' in se_resnet.py just prepared for cifar10 dataset?

**Comment by moskomule** [comment]
Of course, you can use them for other networks, but I assumed the inputs are small (e.g., 32x32) for CifarSEResNet.

**Comment by kp-1** [comment]
Ok ,thanks!!!!
