### ISSUE TITLE
Sorry to bother you again, Can you give some advice use senet for 3d image

### ISSUE THREAD

**Issue by zz10001** [moskomule/senet.pytorch#62]
Hi,

Thanks for your great work, I get some troubles when it use to 3d image. for example, my input shape is (BCZWH--1-1-4-160-160). when I use nn.AdaptiveAvgPool3d(1), it worked like this
![image](https://user-images.githubusercontent.com/39954774/80097571-1614a480-859e-11ea-93a7-9043325a6057.png)
![image](https://user-images.githubusercontent.com/39954774/80097580-1ad95880-859e-11ea-99ea-98fe8ba22945.png)
And when I change `self.avg_pool = nn.AdaptiveAvgPool3d((4,40,40))`,another bug occurs
![image](https://user-images.githubusercontent.com/39954774/80098026-c97d9900-859e-11ea-8cdb-21674aadeacf.png)

Then I change  `self.att3 = SELayer(channel=64*4*40*40,reduction=16)`, it fixed above problem but display OOM. Are there some wrong steps? Can you give me some advice
![image](https://user-images.githubusercontent.com/39954774/80099480-1c585000-85a1-11ea-90c5-1e5f15a438a5.png)

![image](https://user-images.githubusercontent.com/39954774/80098436-76581600-859f-11ea-822f-3bf695f033f1.png)

**Comment by moskomule** [comment]
Hi, if I understand correctly, you need to reshape `y` like `y.view(b, c)` as https://github.com/moskomule/senet.pytorch/blob/3b2a90ad9bcebe6ef004da614f2ecd2d1e29fdb1/senet/se_module.py#L17, as of the first problem.

**Comment by zz10001** [comment]
Hi， 

Thanks for your kind help! I think i have fixed it!!
![image](https://user-images.githubusercontent.com/39954774/80165493-2d8b7600-860e-11ea-8884-5d21362cf7b3.png)
