### ISSUE TITLE
'NoneType' object has no attribute 'topk'

### ISSUE THREAD

**Issue by 123chengbo** [moskomule/senet.pytorch#65]
when i use : pip install -U git+https://github.com/moskomule/homura@v0.6,
i met the error:
File "/root/anaconda2/envs/py37/lib/python3.7/site-packages/homura/callbacks/metrics.py", line 145, in accuracy
    _, pred_idx = output.topk(self.top_k, dim=1)
'NoneType' object has no attribute 'topk'

when i use :pip install -U git+https://github.com/moskomule/homura@v0.7
i met the error:
/root/anaconda2/envs/py37/lib/python3.7/site-packages/torch/utils/cpp_extension.py:191: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

how can i deal with it?

**Comment by moskomule** [comment]
Hi, I updated this repository, so please check README.md and try it again.
