### ISSUE TITLE
ImportError: cannot import name 'DATASET_REGISTRY'

### ISSUE THREAD

**Issue by Kaimingfan** [moskomule/senet.pytorch#68]
When I run python cifar.py,I meet the following errors.
Traceback (most recent call last):
  File "cifar.py", line 5, in <module>
    from homura.vision import DATASET_REGISTRY
ImportError: cannot import name 'DATASET_REGISTRY'

**Comment by moskomule** [comment]
Hi, try: `pip install -U git+https://github.com/moskomule/homura@v2020.07`. The instruction in the README was wrong, and now it is fixed.

**Comment by Kaimingfan** [comment]
Does this version support python3.6.10，pytorch1.2.0, torchvision0.4.0?

**Comment by moskomule** [comment]
Unfortunately not. It only supports Python>=3.8.

**Comment by Kaimingfan** [comment]
ok, thank u very much
