### ISSUE TITLE
Obtain pytorch model trained on ImageNet

### ISSUE THREAD

**Issue by Haoyanlong** [moskomule/senet.pytorch#7]
Could you provide the pytorch model trained on ImageNet???Thank you!!!

**Comment by moskomule** [comment]
Hi, of course, I'd like to. 
Don't you know a good way to distribute 100MB weight freely?

**Comment by engharat** [comment]
hi,
I would like to have the SE-Resnet50 pytorch pretrained on ImageNet weights too! ;)
I think you could put it on a google drive space, setting the file shareable with anyone, I often see pretrained model weights shared on google drive ;)

**Comment by moskomule** [comment]
Hi, thank you for your advice. I'll do so.

**Comment by moskomule** [comment]
I've added the weight https://github.com/moskomule/senet.pytorch/blob/master/README.md .

**Comment by HiKapok** [comment]
Hi, here is one TensorFlow SE-Net with pretrained wieghts converted from Caffe. See [here](https://github.com/HiKapok/TF_Se_ResNe_t)  if you are interested in.
