### ISSUE TITLE
Where is the callbacks module in homura directory?

### ISSUE THREAD

**Issue by woshihaozhu** [moskomule/senet.pytorch#71]
**from homura import callbacks, init_distributed, lr_scheduler, optim, reporters, is_distributed**

I have installed the homura package with the  [github link](https://github.com/moskomule/homura), but the callback module still can't find, so How can i fix the error, thanks very much.

**Comment by moskomule** [comment]
Here https://github.com/moskomule/homura/tree/v2020.07/homura/callbacks

**Comment by woshihaozhu** [comment]
Thank you, that's great
