### ISSUE TITLE
Document is missing

### ISSUE THREAD

**Issue by tongxiaozhong14** [moskomule/senet.pytorch#72]
Dear author, thank you very much for your code, but your code seems to lack homura-related documents.

**Comment by moskomule** [comment]
Hi, what information do you think lacks?

**Comment by sdds-torch** [comment]
Dear author,thank you very much for your code,but I can't find callbacks in homura.Can you upload?

**Comment by moskomule** [comment]
Try `pip install git+https://github.com/moskomule/homura@v2020.07`
