### ISSUE TITLE
Different learning rates for different parameters 

### ISSUE THREAD

**Issue by CharviVitthal** [moskomule/senet.pytorch#75]
Hi, 

I want to use different learning rates for different parameters during training. To do that, I have changed in the main code (cifar.py). I have changed the line `optimizer = optim.SGD(lr=1e-1, momentum=0.9, weight_decay=1e-4)` to 
`optimizer = optim.SGD([{'params': base_params}, {'params': params, 'lr':'1e-4'}], lr=1e-1, momentum=0.9, weight_decay=1e-4)` by defining `params `and `base_params ` by following this [link](https://discuss.pytorch.org/t/how-to-set-a-different-learning-rate-for-a-single-layer-in-a-network/48552/10 ) . I get the error `TypeError: SGD() got multiple values for argument ‘lr’  `

I also tried `optimizer = optim.SGD([{'params':base_params, 'lr':1e-1}, {'params':params, 'lr':1e-4}], momentum=0.9, weight_decay=1e-4)` keeping everything else same. In this case, I get the error: 
```
File "cifar.py", line 251, in main
    with Trainer(model, optimizer, F.cross_entropy, scheduler=scheduler, callbacks=_callbacks) as trainer:
  File "/usr/local/lib/python3.8/site-packages/homura/trainers.py", line 519, in __init__
    super(SupervisedTrainer, self).__init__(model, optimizer, loss_f, callbacks=callbacks, scheduler=scheduler,
  File "/usr/local/lib/python3.8/site-packages/homura/trainers.py", line 121, in __init__
    self.set_optimizer()
  File "/usr/local/lib/python3.8/site-packages/homura/trainers.py", line 422, in set_optimizer
    self.optimizer = optimizer(self.model.parameters())
  File "/usr/local/lib/python3.8/site-packages/torch/optim/sgd.py", line 57, in __init__
    if lr is not required and lr < 0.0:
TypeError: '<' not supported between instances of 'list' and 'float'
```

Any suggestions to solve this issue are welcome and deeply appreciated! :) 

Best,
Charvi

**Comment by moskomule** [comment]
Check https://pytorch.org/docs/stable/optim.html and https://github.com/moskomule/homura/blob/4417780edda77c4643ee6d540d1b9e058f0224c2/examples/cifar10.py#L24.

**Comment by CharviVitthal** [comment]
I seem to have followed exactly the same procedure as in cifar10.py (from the link you shared), defining set_optimizer(trainer) and setting SupervisedTrainer.set_optimizer = set_optimizer but I can't get it to work. I get this error : 
```
File "cifar_joint_try5.py", line 242, in <module>
    main()
  File "cifar_joint_try5.py", line 219, in main
    with Trainer(model, optimizer, F.cross_entropy, scheduler=scheduler, callbacks=_callbacks) as trainer:
  File "/usr/local/lib/python3.8/site-packages/homura/trainers.py", line 519, in __init__
    super(SupervisedTrainer, self).__init__(model, optimizer, loss_f, callbacks=callbacks, scheduler=scheduler,
  File "/usr/local/lib/python3.8/site-packages/homura/trainers.py", line 122, in __init__
    self.set_scheduler()
  File "/usr/local/lib/python3.8/site-packages/homura/trainers.py", line 456, in set_scheduler
    self.scheduler = scheduler(self.optimizer)
  File "/usr/local/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 346, in __init__
    super(StepLR, self).__init__(optimizer, last_epoch)
  File "/usr/local/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 30, in __init__
    raise TypeError('{} is not an Optimizer'.format(
TypeError: partial is not an Optimizer 
``` 
So, seems like the optimizer is not set properly. Any suggestions to solve this issue? 

Best,
Charvi 

Best,
Charvi

**Comment by moskomule** [comment]
`homura.optim` uses partial functions to make it simple.

```python
def set_optimizer(trainer):
    ...
    optim_params = [{"params": params_1}, {"params": params_2, "lr": 0.01}]
    trainer.optimizer = torch.optim.SGD(optim_params, lr=1e-1, momentum=0.9)
    trainers.SupervisedTrainer.set_optimizer = set_optimizer
```

This would set the learning rate of `params_2` to 0.01 and that of `params_1` to 0.1.

**Comment by CharviVitthal** [comment]
Thanks, It is working. The problem was that in my code, I confused between your optim functions and torch.optim. 
Best,
Charvi
