### ISSUE TITLE
Pretrained weights cannot be used

### ISSUE THREAD

**Issue by achaiah** [moskomule/senet.pytorch#9]
Hi I tried using your pretrained weights file following your README
```
senet = se_resnet50(num_classes=1000)
senet.load_state_dict(torch.load("weight.pkl"))
```

However, there seems to be an issue with the file.  I get an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 355, in load_state_dict
    .format(name))
KeyError: 'unexpected key "weight" in state_dict'
```
It seems that the file is saved with some extra parameters that cannot be read back out. I'm not sure what the issue is but googling I found [this discussion](https://github.com/yunjey/pytorch-tutorial/issues/6) that may be useful in troubleshooting.

Thanks

**Comment by achaiah** [comment]
Nevermind, I had to rework the dict items a bit because they weren't saved in the same convention as the official pytorch models, however, there is still a problem with actual weights themselves.
```
    model.load_state_dict(new_state_dict)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 360, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: invalid argument 2: sizes do not match at /opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/THC/generic/THCTensorCopy.c:95
```
Looks like the saved model doesn't match the vanilla one that I create with
```
senet = se_resnet50(num_classes=1000)
senet.load_state_dict(torch.load("weight.pkl"))
```

**Comment by moskomule** [comment]
Do you use PyTorch v0.3.0, right? Then 

```
senet.load_state_dict(torch.load("weight.pkl"), strict=False)
```
works.

**Comment by achaiah** [comment]
Hmm sorry but it does not work for me. I get:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 482, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: invalid argument 2: sizes do not match at /opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/generic/THCTensorCopy.c:101

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_classifier.py", line 445, in <module>
    main(get_opts())
  File "train_classifier.py", line 357, in main
    resumeModel=opt['resumeModel'])
  File "train_classifier.py", line 178, in get_model
    model.load_state_dict(new_state_dict, strict=False)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 487, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named fc.weight, whose dimensions in the model are torch.Size([1096, 2048]) and whose dimensions in the checkpoint are torch.Size([1000, 2048]).
```

**Comment by achaiah** [comment]
Alright, I got it to work. Main issue was that I'm using a different number of classes. For anyone else who is looking to re-use the pretrained model here's some useful code:
```
model = se_resnet.se_resnet50(num_classes=1000)
state_dict = torch.load('weight.pkl')['weight']
from collections import OrderedDict
new_state_dict = OrderedDict()
for k, v in state_dict.items():
    name = k[7:]  # remove `module.`
    new_state_dict[name] = v

model.load_state_dict(new_state_dict, strict=False)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, num_classes)
```
The pretrained weights were trained with DataParallel and so the dictionary has to be preprocessed to remove the 'module' attribute.  Then need to replace the class count with your own by replacing the fully connected layer.

**Comment by lxtGH** [comment]
Thanks for your codes！

**Comment by lxtGH** [comment]
Hi @achaiah  I use your code, but I found this error.

RuntimeError: While copying the parameter named layer2.0.se.fc.0.weight, whose dimensions in the model are torch.Size([32, 512]) and whose dimensions in the checkpoint are torch.Size([16, 512]).

**Comment by achaiah** [comment]
It looks like there is a mismatch in the FC layer. Are you sure that the pretrained model weights you're using are from exactly the same model that you're loading in step 1?

**Comment by 22wei22** [comment]
@achaiah    I have a problem.when i tun torch.load('weight.pkl')['weight'] and torch.load('weight.pkl') .I get the same result.what does ['weight'] do?

**Comment by 22wei22** [comment]
Hi,I get the same errer.RuntimeError: While copying the parameter named layer2.0.se.fc.0.weight, whose dimensions in the model are torch.Size([32, 512]) and whose dimensions in the checkpoint are torch.Size([16, 512]).  Have you solve it?

**Comment by achaiah** [comment]
@22wei22  `['weight']` is simply a key in the dictionary that you get from `torch.load('weight.pkl')`.  The size mismatch indicates that the pretrained model weights you're trying to load do not fit the model.

**Comment by HiKapok** [comment]
Hi, you also can try  [this](https://github.com/HiKapok/TF_Se_ResNe_t) with pretrained wieghts converted from Caffe if you'd like to use TensorFlow.

**Comment by Xingxiangrui** [comment]
Maybe you can use this code and pretrained SENet model. I can run it and get pretrained models without bugs: https://github.com/Xingxiangrui/various_pyTorch_network_structure/blob/master/senet_and_pretrained.py
